<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AssemblyName>OLA3D.Calculator</AssemblyName>
    <RootNamespace>OLA3D.Calculator</RootNamespace>
    <Version>1.0.0</Version>
    <AssemblyVersion>1.0.0.0</AssemblyVersion>
    <FileVersion>1.0.0.0</FileVersion>
    <Product>OLA3D Calculator</Product>
    <Title>OLA3D Calculator</Title>
    <Authors>OLA3D</Authors>
    <Company>OLA3D</Company>
    <Copyright>Copyright © 2026 OLA3D</Copyright>
    <Description>CAD design and multi-material 3D printing price calculator.</Description>
    <ApplicationIcon>app.ico</ApplicationIcon>
    <DebugType>none</DebugType>
    <DebugSymbols>false</DebugSymbols>
    <IncludeSourceRevisionInInformationalVersion>false</IncludeSourceRevisionInInformationalVersion>
  </PropertyGroup>
</Project>
